import React from 'react';
import Announcement from '@/components/Announcement';
import type { AnnouncementProps } from '@/components/Announcement';
import Media, { MediaProps } from '@/components//Media';

const now = new Date();
const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);
const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000);
const nextWeek = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);

export const sampleMedia: MediaProps[] =   [
  {
    id: 1,
    file: '/demo-media/integral-fest.png',
    name: 'Integral fest',
    createdAt: now,
    mediaType: 'image',
    alt: 'Integral Fest image',
  },
  {
    id: 2,
    file: '/demo-media/sample.mp4',
    name: 'Introduction Video',
    createdAt: now,
    mediaType: 'video',
    alt: 'Language classes video',
    autoPlay: true,
    caption: 'Zapisy na lektoraty w semestrze letnim 2024/2025/ Registration for foreign language classes in the summer semester 2024/2025',
  },
  {
    id: 3,
    file: '/demo-media/library.gif',
    name: 'Library Course Announcement',
    createdAt: now,
    mediaType: 'gif',
    alt: 'Library animation',
  },
];


export const sampleAnnouncements: AnnouncementProps[] = [
  {
    id: 1,
    name: 'Dean Office Hours',
    message: '08.05.2025 from 12:00 godziny dziekańskie z okazji Całkonaliów / hours free from classes due to Integral Fest. 08.05.2025 from 12:00 godziny dziekańskie z okazji Całkonaliów / hours free from classes due to Integral Fest. 08.05.2025 from 12:00 godziny dziekańskie z okazji Całkonaliów / hours free from classes due to Integral Fest. 08.05.2025 from 12:00 godziny dziekańskie z okazji Całkonaliów / hours free from classes due to Integral Fest. 08.05.2025 from 12:00 godziny dziekańskie z okazji Całkonaliów / hours free from classes due to Integral Fest.',
    groupId: 1,
    userId: 101,
    startDate: yesterday,
    endDate: tomorrow,
    createdAt: now,
    mediaId: 1,
  },
  {
    id: 2,
    name: 'Language classes',
    message: 'Zapisy na lektoraty w semestrze letnim 2024/2025/ Registration for foreign language classes in the summer semester 2024/2025Zapisy na lektoraty w semestrze letnim 2024/2025/ Registration for foreign language classes in the summer semester 2024/2025Zapisy na lektoraty w semestrze letnim 2024/2025/ Registration for foreign language classes in the summer semester 2024/2025Zapisy na lektoraty w semestrze letnim 2024/2025/ Registration for foreign language classes in the summer semester 2024/2025',
    groupId: 2,
    userId: 102,
    startDate: now,
    endDate: nextWeek,
    createdAt: now,
    mediaId: 2, 
  },
  {
    id: 3,
    name: 'Library Course',
    message: 'ekurs Przysposobienie biblioteczne/ Library Training e-course ekurs Przysposobienie biblioteczne/ Library Training e-course ekurs Przysposobienie biblioteczne/ Library Training e-course ekurs Przysposobienie biblioteczne/ Library Training e-course ekurs Przysposobienie biblioteczne/ Library Training e-course ekurs Przysposobienie biblioteczne/ Library Training e-course',
    groupId: 3,
    userId: 103,
    startDate: yesterday,
    endDate: tomorrow,
    createdAt: now,
    mediaId: undefined, 
  },
  {
    id: 4,
    name: 'Library Course',
    message: 'ekurs Przysposobienie biblioteczne/ Library Training e-course',
    groupId: 3,
    userId: 103,
    startDate: tomorrow,
    endDate: nextWeek,
    createdAt: now,
    mediaId: undefined, 
  },
  {
    id: 5,
    name: 'Library Course',
    message: 'ekurs Przysposobienie biblioteczne/ Library Training e-course',
    groupId: 3,
    userId: 103,
    startDate: new Date('2025-01-01'),
    endDate: new Date('2025-02-01'),
    createdAt: now,
    mediaId: undefined, 
  },
  {
    id: 6,
    name: 'Library Course',
    message: 'ekurs Przysposobienie biblioteczne/ Library Training e-course ekurs Przysposobienie biblioteczne/ Library Training e-course ekurs Przysposobienie biblioteczne/ Library Training e-course ',
    groupId: 3,
    userId: 103,
    startDate: yesterday,
    endDate: nextWeek,
    createdAt: now,
    mediaId: 3, 
  },
  {
    id: 7,
    name: 'Library Course again...',
    message: 'ekurs Przysposobienie biblioteczne/ Library Training e-course ekurs Przysposobienie biblioteczne/ Library Training e-course',
    groupId: 3,
    userId: 103,
    startDate: new Date('2025-04-01'),
    endDate: new Date('2025-05-05'),
    createdAt: now,
    mediaId: undefined, 
  },
  {
    id: 8,
    name: 'Library Course again...',
    message: 'ekurs Przysposobienie biblioteczne/ Library Training e-course ekurs Przysposobienie biblioteczne/ Library Training e-course',
    groupId: 3,
    userId: 103,
    startDate: new Date('2025-04-01'),
    endDate: new Date('2025-05-05'),
    createdAt: now,
    mediaId: undefined, 
  },
  {
    id: 9,
    name: 'Library Course again...',
    message: 'ekurs Przysposobienie biblioteczne/ Library Training e-course ekurs Przysposobienie biblioteczne/ Library Training e-course',
    groupId: 3,
    userId: 103,
    startDate: new Date('2025-04-01'),
    endDate: new Date('2025-05-05'),
    createdAt: now,
    mediaId: undefined, 
  },
  {
    id: 10,
    name: 'Library Course again...',
    message: 'ekurs Przysposobienie biblioteczne/ Library Training e-course ekurs Przysposobienie biblioteczne/ Library Training e-course',
    groupId: 3,
    userId: 103,
    startDate: new Date('2025-04-01'),
    endDate: new Date('2025-05-09'),
    createdAt: now,
    mediaId: undefined, 
  },
  {
    id: 11,
    name: 'Library Course again...',
    message: 'ekurs Przysposobienie biblioteczne/ Library Training e-course ekurs Przysposobienie biblioteczne/ Library Training e-course',
    groupId: 3,
    userId: 103,
    startDate: new Date('2025-04-01'),
    endDate: new Date('2025-05-09'),
    createdAt: now,
    mediaId: undefined, 
  },
  {
    id: 12,
    name: 'Library Course again...',
    message: 'ekurs Przysposobienie biblioteczne/ Library Training e-course ekurs Przysposobienie biblioteczne/ Library Training e-course',
    groupId: 3,
    userId: 103,
    startDate: new Date('2025-04-01'),
    endDate: new Date('2025-05-09'),
    createdAt: now,
    mediaId: undefined, 
  },
  {
    id: 13,
    name: 'Library Course again...',
    message: 'ekurs Przysposobienie biblioteczne/ Library Training e-course ekurs Przysposobienie biblioteczne/ Library Training e-course',
    groupId: 3,
    userId: 103,
    startDate: new Date('2025-04-01'),
    endDate: new Date('2025-05-05'),
    createdAt: now,
    mediaId: undefined, 
  },
  {
    id: 14,
    name: 'Library Course again...',
    message: 'ekurs Przysposobienie biblioteczne/ Library Training e-course ekurs Przysposobienie biblioteczne/ Library Training e-course',
    groupId: 3,
    userId: 103,
    startDate: new Date('2025-04-01'),
    endDate: new Date('2025-05-09'),
    createdAt: now,
    mediaId: undefined, 
  },
];